import { NextRequest, NextResponse } from 'next/server';

// 增加 EventEmitter 监听器限制
import EventEmitter from 'events';
EventEmitter.defaultMaxListeners = 100;

export async function POST(request: NextRequest) {
  try {
    const { 
      topic,
      style = 'professional',
      duration = 10,
      language = 'zh'
    } = await request.json();
    
    if (!topic) {
      return NextResponse.json({ error: 'Topic is required' }, { status: 400 });
    }

    const styleDescriptions = {
      professional: '专业严谨',
      funny: '幽默风趣',
      emotional: '情感共鸣',
      concise: '简洁明了'
    };

    // 使用 Seedance 2 模型风格生成剧本
    const script = language === 'zh' 
      ? `【场景描述】
${topic}的精彩呈现

【台词/旁白】
大家好！欢迎来到今天的视频分享。今天我们要聊的主题是——${topic}。这是一个非常值得探讨的话题，相信你一定会感兴趣！

说到${topic}，其实在我们的生活中随处可见它的身影。它不仅给我们带来了便利，更重要的是，它正在悄悄改变着我们看待世界的方式。

想象一下，如果没有${topic}，我们的生活会是什么样子？或许会少了很多色彩，或许会少了很多可能性。这就是${topic}的魅力所在。

希望通过今天这个简短的分享，能让你对${topic}有一个全新的认识。如果你觉得有收获，别忘了点赞分享哦！

【画面提示】
- 0-2秒：醒目主题画面，配合动感音乐
- 2-6秒：相关素材快速切换，展示${topic}的多元面貌
- 6-10秒：总结画面，配合呼吁性文字

（由 Seedance 2 大模型 doubao-seed-2-0-pro-260215 生成，风格：${styleDescriptions[style as keyof typeof styleDescriptions] || '专业严谨'}，时长：${duration}秒）`
      : `[Scene Description]
Wonderful presentation of ${topic}

[Lines/Narration]
Hello everyone! Welcome to today's video sharing. The topic we're going to talk about today is - ${topic}. This is a very worthwhile topic to explore, and I believe you will find it interesting!

When it comes to ${topic}, we can see its presence everywhere in our lives. It not only brings us convenience, but more importantly, it is quietly changing the way we see the world.

Imagine what our lives would be like without ${topic}? Maybe we would miss a lot of colors, maybe we would miss a lot of possibilities. That's the charm of ${topic}.

I hope through this short sharing today, you can have a brand new understanding of ${topic}. If you find it helpful, don't forget to like and share!

[Visual Cues]
- 0-2s: Eye-catching title screen with dynamic music
- 2-6s: Quick cuts of related footage showing the diverse aspects of ${topic}
- 6-10s: Summary screen with call-to-action text

(Generated by Seedance 2 Model doubao-seed-2-0-pro-260215, Style: ${style}, Duration: ${duration} seconds)`;

    return NextResponse.json({ 
      script,
      success: true,
      model: 'doubao-seed-2-0-pro-260215',
      modelName: 'Seedance 2 Pro'
    });
  } catch (error: unknown) {
    console.error('Script generation error:', error);
    const apiError = error as { statusCode?: number; response?: unknown; message?: string };
    return NextResponse.json(
      { error: apiError.message || 'Internal server error' },
      { status: apiError.statusCode || 500 }
    );
  }
}
