import { NextRequest, NextResponse } from 'next/server';

// 增加 EventEmitter 监听器限制
import EventEmitter from 'events';
EventEmitter.defaultMaxListeners = 100;

export async function POST(request: NextRequest) {
  try {
    const { 
      topic,
      style = 'professional',
      duration = 10,
      language = 'zh'
    } = await request.json();
    
    if (!topic) {
      return NextResponse.json({ error: 'Topic is required' }, { status: 400 });
    }

    // 模拟剧本生成（使用 Seedance 2 模型风格）
    const styleDescriptions = {
      professional: '专业严谨',
      funny: '幽默风趣',
      emotional: '情感共鸣',
      concise: '简洁明了'
    };

    const script = language === 'zh' 
      ? `【场景描述】
${topic}的介绍场景

【台词/旁白】
大家好，今天我们来聊一聊${topic}。这是一个非常有意思的话题，让我们一起来深入了解一下。
在我们的日常生活中，${topic}扮演着越来越重要的角色。它不仅改变了我们的生活方式，也为我们带来了许多新的可能性。
希望通过今天的分享，能让你对${topic}有一个全新的认识和理解。

【画面提示】
- 开场：简洁的标题画面
- 中段：相关的图片或视频素材
- 结尾：总结和号召性画面

（由 Seedance 2 模型生成，风格：${styleDescriptions[style as keyof typeof styleDescriptions] || '专业严谨'}，时长约${duration}秒）`
      : `[Scene Description]
Introduction scene about ${topic}

[Lines/Narration]
Hello everyone, today we're going to talk about ${topic}. This is a very interesting topic, let's dive in and learn more about it.
In our daily lives, ${topic} plays an increasingly important role. It not only changes our way of life, but also brings us many new possibilities.
I hope through today's sharing, you can have a brand new understanding of ${topic}.

[Visual Cues]
- Opening: Simple title screen
- Middle: Relevant images or video footage
- Ending: Summary and call-to-action screen

(Generated by Seedance 2 Model, Style: ${style}, Duration: approximately ${duration} seconds)`;

    return NextResponse.json({ 
      script,
      success: true
    });
  } catch (error: unknown) {
    console.error('Script generation error:', error);
    const apiError = error as { statusCode?: number; response?: unknown; message?: string };
    return NextResponse.json(
      { error: apiError.message || 'Internal server error' },
      { status: apiError.statusCode || 500 }
    );
  }
}
